# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("factor_model_with_covariates", "factor_model_without_covariates", "model1", "model1_gammaOmega", "model2", "model3", "model4", "model5", "model6", "model7", "model8")

# load each stan module
Rcpp::loadModule("stan_fit4factor_model_with_covariates_mod", what = TRUE)
Rcpp::loadModule("stan_fit4factor_model_without_covariates_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model1_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model1_gammaOmega_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model2_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model3_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model5_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model6_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model7_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model8_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
